development:
  password: bc900c44e6590205bb6edb64a6ec35cb
  theme_id: 51079872574
  store: https://spro-com.myshopify.com
# production:
  # password: 72925032fee5db9c9aa623443fded3bd
  # theme_id: 49983979582
  # store: aerocaredirect.myshopify.com