development:
  password: bc900c44e6590205bb6edb64a6ec35cb
  theme_id: 50822840382
  store: https://spro-com.myshopify.com
# production:
  # password: 72925032fee5db9c9aa623443fded3bd
  # theme_id: 75516018722
  # store: aerocaredirect.myshopify.com